import NavBar from '@/components/NavBar' 
import './globals.css'
import { Inter } from 'next/font/google' 

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
    title: 'Joan Amudu',
    description: 'Full-Stack Engineer portfolio generated by create next app',
}

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body className={inter.className}><NavBar/>{children}</body>
        </html>
    )
}
